### ISSUE TITLE
Update benchmark result

### ISSUE THREAD

**Issue by sainnhe** [delphinus/artify.nvim#2]
Hello! I'm the author of artify.vim, thanks for your implementation! It's much faster than my pure vim script implementation.

I just optimized the performance of my plugin, and also mentioned your implementation in README, see [this commit](https://github.com/sainnhe/artify.vim/commit/372f6163903566605ecce75a7dcfd0a6e49b7292)

It's about 30 times faster than before, but it's still much slower than yours. Here is my new benchmark result:

```
0.222341
0.0051669999999999
```

Could you update your benchmark result in README? Thanks!

---

I optimized the performance again, it's about 2 times faster than before, but still much slower than yours.

```
0.133174
0.005158
```

**Comment by delphinus** [comment]
I updated README with your updated results. And thank you for your brilliant concept of the original artify.vim!! I have been using this long days, so am very happy to hear your voice directly :)

**Comment by sainnhe** [comment]
Thank you! Great work in lua implementation ;)
