### ISSUE TITLE
Use lualines format option as example

### ISSUE THREAD

**Issue by shadmansaleh** [delphinus/artify.nvim#3]
I just saw this plugin . It seems nice :)
Currently the example is:
```lua
local artify = require'artify'
local lualine = require'lualine'
local mode = require'lualine.components.mode'
lualine.sections.lualine_a = {
  function()
    return artify(mode(), 'monospace')
  end,
}
```

I think this might be better

```lua
local artify = require'artify'
local lualine = require'lualine'
lualine.sections.lualine_a = {{'mode',
  format = function(mode_name)
    return artify(mode_name, 'monospace')
  end,}
}
```

The format option was added for component result manupulation . 

format options description in lualines README
> Takes a function . The funtion gets the result of component as argument and it's return value is displayed. So this function can parse and format the output as user wants.

I think that fits well here . Also currently many components have initialization section and soon  they will be replaced by oop styled classes . That will break current example. Even currently it's not possible to do 
`local mode = require'lualine.components.mode'`
for most components .The mode component is rather an exception. So I think it's better to leave component initialization to lualine. :)

**Comment by delphinus** [comment]
Thank you! How nice feature has arrived at lualine!
